### ISSUE TITLE
Incompatible with mariadb 10.11

### ISSUE THREAD

**Issue by kuon** [libracore/frappe#45]
This comparison:

https://github.com/libracore/frappe/blob/466feea9d11c5a0ea23388906c30ce5f9703c791/frappe/database/mariadb/setup_db.py#L104

does not work with mariadb 10.11 as 10.11 is smaller than 10.2.

I can make a pull request, but as it's a very simple fix, I thought it would be simpler to just write it directly. Also I suggest to commit it to branch `v12` which is what most people will use with `erpnextswiss`.

simple fix:

```diff
- if versions['major'] <= '10.2':
```

```diff
+ from packaging import version as semver
	
+ if semver.parse(versions['major']) <= semver.parse("10.2"):
```

**Comment by lasalesi** [comment]
Thanks for your input. We have removed this as 10.2 and prior are probably no longer in productive use and we use the current configuration for all.
